Deliverable2
valp0/academy-go-q32021 pull request #5
Opened 2021-10-09 04:39 UTC by valp0

Refactored for clean architecture purposes. Added /fetch endpoint to fetch pokémons from the PokéAPI. Added unit tests.

2021-10-09 18:12 UTC, MigGrover requested changes
Por favor tener en cuenta los comentarios y reparar el test

2021-10-09 18:12 UTC, MigGrover commented on app/app.go
> +	r := repo.Repo{}
por que aqui repo no lleva el mismo patron es decir repository.NewRepo...

2021-10-09 18:12 UTC, MigGrover commented on common/random.go
> +	if 1 > num || num > 898 {
aqui estos valores 1 y 898 pueden ser constantes

2021-10-09 18:12 UTC, MigGrover commented on common/random.go
> +	if 1 > num || num > 898 {
aqui el uso de constantes

2021-10-09 18:12 UTC, MigGrover commented on services/readSvc_test.go
> +			"wrong path error",
este testcase esta fallando

2021-10-09 18:12 UTC, MigGrover commented on services/readSvc.go
> +func NewReadSvc(repo repository) readSvc {
Comentarios de exportasion

2021-10-09 18:12 UTC, MigGrover commented on services/fetchSvc_test.go
> +var mockedGet = func(url string) (*http.Response, error) {
esto es una logica considerable para una funcion get que esta siendo mockeada

2021-10-09 18:12 UTC, MigGrover commented on services/fetchSvc.go
> +func NewFetchSvc(repo repository) fetchSvc {
comentarios de funciones exportadas

2021-10-09 18:12 UTC, MigGrover commented on services/fetchSvc.go
> +	url := "https://pokeapi.co/api/v2/pokemon-form/" + strconv.Itoa(idInt)
quiza esto deberias guardarlo como una constante

2021-10-09 18:12 UTC, MigGrover commented on handlers/fetch.go
> +func NewFetchHandler(service fetch) fetchHandler {
comentarios de exportasion de funcion

2021-10-09 18:12 UTC, MigGrover commented on handlers/home.go
> +type iHomeHandler interface {
deberias de respetar la convencion jeje o todos con el i o todos sin el i

2021-10-09 18:12 UTC, MigGrover commented on repo/api.go
> +func (r Repo) CallPokeApi(url, path string) ([]common.Element, error) {
aqui no confundir una cosa es tu repositorio del csv y otra un repositorio o cliente http, es decir son entidades diferentes que conducen a infraestructuras diferentes.
pokemonRepo -> operaciones csv.
pokemonAPIRepo -> operaciones http

2021-10-09 18:12 UTC, MigGrover commented on repo/api.go
> +func addPokemon(id int, name, path string) (bool, error) {
esto deberia estar en el otro repositorio. es decir el que tiene la logica de tu csv

2021-10-09 18:12 UTC, MigGrover commented on handlers/read.go
> +		if len(err.Error()) > 51 && err.Error()[len(err.Error())-51:] == "is not a valid ID, please use integers for ID field" ||
Aqui creo que podrias hacer un manejo diferente de los errores. de este modo esta muy "hard coded" lo cual es una mala practica, ademas que basarse en el len no es buena idea

2021-10-11 21:19 UTC, valp0 commented on services/readSvc_test.go
> +			"wrong path error",
![image](https://user-images.githubusercontent.com/75410408/136856755-7db83f03-fc5a-449a-ac19-585005dce01a.png)

Me parece que está funcionando bien (no he modificado nada).

2021-10-14 00:24 UTC, merged